In [8]:
# Câu 1: Phép toán cơ bản trên vector và ma trận (15 điểm)
import numpy as np
from numpy.linalg import norm
from math import acos, degrees
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],[0, 3, 4],[2, -1, 0]])
tongAB = A+B
tichAB= 3*A - 2*B
dot= np.dot(A, B)
cos = dot/(norm(A)*norm(B))
goc = degrees(acos(cos))
CtC = np.dot(C.T, C)
print("a) A + B =", tongAB)
print("   3A - 2B =", tichAB)
print("\nb) A · B =", dot)
print("   Góc giữa A và B (độ):", round(goc, 3))
print("\nc) C^T · C =\n", CtC)

a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]

b) A · B = -8
   Góc giữa A và B (độ): 108.376

c) C^T · C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [9]:
# Câu 2: Nhân ma trận, định thức và hạng ma trận (20 điểm)
M = np.array([[1, 2, 3, 0],[4, 5, 6, 1],[7, 8, 9, 2],[0, 1, 1, 0]])
N = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[12, 13, 14, 15]])
tichMN = np.dot(M, N)
try:
    detM = np.linalg.det(M)
except np.linalg.LinAlgError:
    detM = "Không phải ma trận vuông"
rankN = np.linalg.matrix_rank(N)
print("a) M x N =\n", tichMN)
print("\nb) Định thức của M =", round(detM, 3))
print("\nc) Hạng của ma trận N =", rankN)

a) M x N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M = 0.0

c) Hạng của ma trận N = 2


In [14]:
# Câu 3: Nghịch đảo ma trận và giải hệ phương trình (25 điểm)
P = np.array([[2, 1, 0, 1],[0, 3, 1, -1],[1, 0, 4, 2],[0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
try:
    Pinv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P là:\n", Pinv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (det = 0)")
if 'Pinv' in locals():
    x = np.dot(Pinv, b)
    print("\nb) Nghiệm của hệ phương trình là:\n", x)
    print(f"x = {x[0]}")
    print(f"y = {x[1]}")
    print(f"z = {x[2]}")
    print(f"w = {x[3]}")
if 'x' in locals():
    check = np.dot(P, x)
    print("\nc) Kiểm tra: P · x =\n", check)
    print("So sánh với b =\n", b)


a) Ma trận nghịch đảo của P là:
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm của hệ phương trình là:
 [0.46511628 2.10465116 1.65116279 0.96511628]
x = 0.4651162790697674
y = 2.1046511627906974
z = 1.6511627906976745
w = 0.9651162790697675

c) Kiểm tra: P · x =
 [4. 7. 9. 5.]
So sánh với b =
 [4 7 9 5]


In [15]:
# Câu 4: Giá trị riêng, vector riêng và chuẩn hóa (20 điểm)
Q = np.array([[4, -1, 0],[1, 3, -2],[0, 1, 2]])
gtr, vtr = np.linalg.eig(Q)
print("a) Các giá trị riêng của Q:")
print(gtr)
print("\nb) Các vector riêng tương ứng (cột):")
print(vtr)
vtchuanhoa = np.array([vec / np.linalg.norm(vec) for vec in vtr.T]).T
print("\nc) Các vector riêng đã chuẩn hóa:")
print(vtchuanhoa)

a) Các giá trị riêng của Q:
[3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]

b) Các vector riêng tương ứng (cột):
[[0.83327121+0.j         0.26206044+0.31354813j 0.26206044-0.31354813j]
 [0.455468  +0.j         0.78166743+0.j         0.78166743-0.j        ]
 [0.31338154+0.j         0.21963176-0.41685708j 0.21963176+0.41685708j]]

c) Các vector riêng đã chuẩn hóa:
[[0.83327121+0.j         0.26206044+0.31354813j 0.26206044-0.31354813j]
 [0.455468  +0.j         0.78166743+0.j         0.78166743-0.j        ]
 [0.31338154+0.j         0.21963176-0.41685708j 0.21963176+0.41685708j]]


In [18]:
# Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích (20 điểm)
R = np.array([[1, -2, 3],[2, 0, 1],[-1, 1, 4]])
b = np.array([10, 8, 7])
x1 = np.linalg.solve(R, b)
print("a) Nghiệm hệ phương trình Rx = b là:\n", x1)
detR = np.linalg.det(R)
print("\nb) Định thức của R:", detR)
if detR != 0:
    Rinv = np.linalg.inv(R)
    x2 = np.dot(Rinv, b)
    print("Ma trận R khả nghịch. Nghiệm tìm bằng R^-1 · b là:\n", x2)
    print("So sánh hai nghiệm (x1 == x2?):", np.allclose(x1, x2))
else:
    print("Ma trận R không khả nghịch, không thể giải bằng nghịch đảo.")
cauc = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của R là:", round(cauc, 4))

a) Nghiệm hệ phương trình Rx = b là:
 [2.7826087  0.04347826 2.43478261]

b) Định thức của R: 23.0
Ma trận R khả nghịch. Nghiệm tìm bằng R^-1 · b là:
 [2.7826087  0.04347826 2.43478261]
So sánh hai nghiệm (x1 == x2?): True

c) Chuẩn Frobenius của R là: 6.0828
