In [6]:
danhsach1 = [1. , 3.] 
danhsach2 = [5. , 7.]
danhsach = danhsach1 + danhsach2
print(danhsach)

[1.0, 3.0, 5.0, 7.0]


In [7]:
danhsach_gapdoi = 2 * danhsach
print(danhsach_gapdoi)

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]


In [8]:
danhsach * 2

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [9]:
danhsach / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [22]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"] 
thu_tu = [2, 3, 4, 1] 
diem_so = [10, 9, 8, 7] 
anh_xa = list(zip(thu_tu, mon_hoc, diem_so) )
anh_xa

[(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)]

In [24]:
tap_hop = set(anh_xa)
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [25]:
lay_TT, lay_monhoc , lay_diem = zip(*anh_xa)
lay_monhoc

('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')

In [16]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5, 10), range(15, 20)))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [17]:
list(zip(range(4), range(7, 12), reversed(range(11) ) ) )

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

In [20]:
a = b = c = 0
mylist = []
execfile('d:/thucthi1.py')

100 200 300


In [26]:
from sympy import Symbol
x = Symbol('x')
f = x + x + x + 2
f

3*x + 2

In [27]:
a = Symbol('Noi') 
b = Symbol('Chim') 
3*b + 7*a

3*Chim + 7*Noi

In [29]:
a = Symbol('Noi')
b = Symbol('Chim') 
a.name 

'Noi'

In [30]:
b.name

'Chim'

In [31]:
from sympy import Symbol
x = Symbol('x') 
y = Symbol('y') 
s = x*y + y*x 
s

2*x*y

In [32]:
p = x*(x+2*x) 
p

3*x**2

In [33]:
p = (x+2)*(y+3) 
p

(x + 2)*(y + 3)

In [34]:
(x + 2)*(y + 3) 
p = (x+2)*(y+3) + (x+2)*(x-3) 
p 

(x - 3)*(x + 2) + (x + 2)*(y + 3)

In [35]:
p = x*(-x+2*x-x)
p

0

In [36]:
p = (x+2)*(y+3)
p.expand()

x*y + 3*x + 2*y + 6

In [37]:
from sympy import factor 
bieuthuc = x**3 - y**3 
factor(bieuthuc)

(x - y)*(x**2 + x*y + y**2)

In [38]:
from sympy import expand 
bieuthuc = (x - y)*(x**2 + x*y + y**2) 
expand(bieuthuc)

x**3 - y**3

In [39]:
from sympy import Symbol 
x = Symbol('x') 
y = Symbol('y') 
bieuthuc = x*x - x*y + y*y 
bieuthuc

x**2 - x*y + y**2

In [40]:
giatri = bieuthuc.subs({x:3, y:2})
giatri

7

In [41]:
x

x

In [42]:
y

y

In [43]:
giatri = bieuthuc.subs({x:3, y:x})
giatri

x**2 - 3*x + 9

In [45]:
from sympy import Symbol 
x = Symbol('x') 
y = Symbol('y') 
bieuthuc = x*x - x*y + y*y 
bieuthuc = x**2 - x*y + y**2 
bieuthuc_moi = bieuthuc.subs({x:1-y})
bieuthuc_moi

y**2 - y*(1 - y) + (1 - y)**2

In [46]:
from sympy import simplify 
dongian = simplify(bieuthuc_moi) 
dongian

3*y**2 - 3*y + 1

In [47]:
from sympy import Symbol 
from sympy import sin, cos 
x = Symbol('x') 
y = Symbol('y') 
bt = sin(x)*cos(y) + cos(x)*sin(y) 
bt_moi = simplify(bt) 
bt_moi 

sin(x + y)

In [48]:
import numpy as np
vec1 = np.array([1., 3., 5.])
vec1 * 2

array([ 2.,  6., 10.])

In [49]:
vec1 * vec1 

array([ 1.,  9., 25.])

In [50]:
vec1 /2 

array([0.5, 1.5, 2.5])

In [51]:
vec1 + vec1 

array([ 2.,  6., 10.])

In [52]:
vec2 = array([2., 4.]) 
vec1 + vec2 

NameError: name 'array' is not defined

In [55]:
vec3 = np.array([2., 4., 6.]) 
vec1 + vec3

array([ 3.,  7., 11.])

In [56]:
vec1 / vec3 

array([0.5       , 0.75      , 0.83333333])

In [57]:
vec1 * vec3 

array([ 2., 12., 30.])

In [58]:
2* vec1 + 5* vec3 

array([12., 26., 40.])

In [59]:
vec3[2]  

6.0

In [60]:
vec4 = np.linspace(0, 20, 5) 
vec4 

array([ 0.,  5., 10., 15., 20.])

In [63]:
vec5 = np.zeros(5) 
vec5

array([0., 0., 0., 0., 0.])

In [64]:
vec6 = np.ones(5)
vec6

array([1., 1., 1., 1., 1.])

In [65]:
vec7 = np.empty(5) 
vec7

array([1., 1., 1., 1., 1.])

In [67]:
np.random.random(5) 

array([0.63326654, 0.36221667, 0.96212999, 0.20520575, 0.79957598])

In [68]:
v = np.array([1., 3., 5.])
np.sum(v)

9.0

In [69]:
v.shape 

(3,)

In [91]:
v.transpose() 

array([1., 2., 5.])

In [71]:
v1 = v[:2] 
v1

array([1., 3.])

In [72]:
v[0] = 5 
v

array([5., 3., 5.])

In [73]:
v1

array([5., 3.])

In [78]:
v1[:2] = [1., 2., 3.]
v1

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [79]:
v1[:2] = [1., 2] 
v 


array([1., 2., 5.])

In [80]:
v3 = 2 * v[:2] + v1 * 3 
v3

array([ 5., 10.])

In [81]:
v1 = [4, 6] 
v3

array([ 5., 10.])

In [82]:
v

array([1., 2., 5.])

In [83]:
v + 10.0

array([11., 12., 15.])

In [84]:
np.sqrt(v) 

array([1.        , 1.41421356, 2.23606798])

In [85]:
np.cos(v) 

array([ 0.54030231, -0.41614684,  0.28366219])

In [86]:
np.sin(v) 

array([ 0.84147098,  0.90929743, -0.95892427])

In [92]:
np.dot(v1, v3) 

80.0

In [93]:
v1.dot(v3) 

AttributeError: 'list' object has no attribute 'dot'

In [94]:
v3.dot(v1) 

80.0

In [95]:
from sympy import Symbol, solve 
x = Symbol('x') 
bieuthuc = x + 3 - 5 
solve(bieuthuc) 


[2]

In [96]:
bieuthuc = x**2 + 3 - 5 
nghiemx = solve(bieuthuc) 
nghiemx 


[-sqrt(2), sqrt(2)]

In [97]:
nghiemx[0] 

-sqrt(2)

In [98]:
nghiemx[1] 

sqrt(2)

In [99]:
from sympy import solve 
x = Symbol('x') 
ptb2 = x**2 + 9*x +8 
solve(ptb2, dict = True) 


[{x: -8}, {x: -1}]

In [100]:
ptb2 = x**2 + 1*x + 10 
nghiemx = solve(ptb2, dict = True) 
nghiemx 


[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]

In [101]:
x = Symbol('x') 
a = Symbol('a') 
b = Symbol('b') 
c = Symbol('c') 
ptb2 = a*x*x + b*x + c 
nghiem = solve(ptb2, x, dict=True) 
nghiem 


[{x: (-b - sqrt(-4*a*c + b**2))/(2*a)}, {x: (-b + sqrt(-4*a*c + b**2))/(2*a)}]

In [102]:
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = 2*x+3*y-12
pt2 = 3*x-2*y-5
solve((pt1, pt2), dict=True)

[{x: 3, y: 2}]

In [110]:
nghiem = solve((pt1, pt2), dict=True)
nghiem = nghiem[0] 
pt1.subs({x:nghiem[x], y:nghiem[y]})

0

In [104]:
pt2.subs({x:nghiem[x], y:nghiem[y]})

0

In [107]:
M1 = np.array([ [9, 12], [23,30] ])
print(M1)

[[ 9 12]
 [23 30]]


In [111]:
u = np.array([ 2, 1]) 
tichM1u = M1.dot(u) 
print(tichM1u) 


[30 76]


In [112]:
tichuM1 = u.dot(M1) 
print(tichuM1) 

[41 54]


In [113]:
np.dot(M1, u) 

array([30, 76])

In [114]:
np.dot(u, M1) 

array([41, 54])

In [116]:
mat1 = np.zeros( [5,5]) 
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [117]:
mat2 = np.ones( [5,5]) 
mat2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [118]:
mat3 = mat1 + 2* mat2
mat3

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [123]:
mat4 = mat3 
mat3[3][2] = 10
mat3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [124]:
mat4

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [125]:
mat5 = np.copy(mat3) 
mat3[3][2] = 10 
mat3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [126]:
mat4

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [127]:
mat5

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2., 10.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [128]:
mat6 = np.empty([4, 5]) 
mat6

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
        1.05699242e-307, 8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.15710088e-306, 6.23056330e-307],
       [1.60219578e-306, 7.56601165e-307, 6.23061763e-307,
        9.34607074e-307, 8.90098127e-307],
       [8.90108313e-307, 6.23053954e-307, 2.22523004e-306,
        2.22522596e-306, 8.34446834e-308]])

In [129]:
mat7 = np.identity(4)  
mat7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
mat8  = np.random.random([4,5]) 
mat8

array([[0.0445392 , 0.66331962, 0.47710565, 0.67054075, 0.10428043],
       [0.75201946, 0.87997229, 0.63865321, 0.03962002, 0.80502039],
       [0.28412318, 0.22691084, 0.38233544, 0.57413261, 0.91944822],
       [0.60659476, 0.57278894, 0.60331986, 0.21475069, 0.16291946]])