In [1]:
#Bai 1:
def scale(a,v):
    return [a * vi for vi in v]
v = [3, 5, 7]
scale(10, v)

[30, 50, 70]

In [2]:
def sumvector(v, w):
    return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w) 

[5, 9, 13]

In [3]:
def dotvector(v, w):
    return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

In [4]:
def lenvector(v):
    return dotvector(v,v)
lenvector(w)

56

In [10]:
#Bai 2:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores

array([-1,  1,  2, -3,  5, -4])

In [11]:
scores >= 0

array([False,  True,  True, False,  True, False])

In [12]:
scores < 0

array([ True, False, False,  True, False,  True])

In [14]:
np.select([scores >=0, scores < 0],["so duong", "so am"])


array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [15]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'])

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [40]:
#Bai 3.1:
from scipy import linalg, sparse
D = np.mat([ [3,4], [5,6] ])
D

matrix([[3, 4],
        [5, 6]])

In [17]:
C = np.mat(np.random.random((5,7)))
C

matrix([[0.01931707, 0.62791201, 0.21651431, 0.96045625, 0.18008396,
         0.88219439, 0.52345459],
        [0.59189958, 0.04675865, 0.34058256, 0.38643957, 0.97220484,
         0.67961385, 0.77685181],
        [0.67210944, 0.09795995, 0.69421445, 0.05072355, 0.60745768,
         0.93513489, 0.86877434],
        [0.02110923, 0.508947  , 0.09622082, 0.20418111, 0.02063138,
         0.64468059, 0.37046607],
        [0.93919079, 0.44427961, 0.658741  , 0.2277253 , 0.94684433,
         0.67892726, 0.62827707]])

In [18]:
A = np.mat(np.random.random((2,2)))
A

matrix([[0.52216941, 0.24216057],
        [0.87697005, 0.37074025]])

In [20]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
b

array([[1.+5.j, 0.+2.j, 0.+3.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [22]:
B

matrix([[1.+5.j, 0.+2.j, 0.+3.j],
        [4.+0.j, 5.+0.j, 6.+0.j]])

In [23]:
A.T

matrix([[0.52216941, 0.87697005],
        [0.24216057, 0.37074025]])

In [24]:
A.I

matrix([[-19.74296875,  12.89573628],
        [ 46.70113971, -27.80700084]])

In [25]:
 linalg.inv(A)

array([[-19.74296875,  12.89573628],
       [ 46.70113971, -27.80700084]])

In [26]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
M_lower

array([[-1,  0,  0],
       [ 0, -2,  0],
       [ 1,  5, -2]])

In [27]:
M_upper = np.triu(M)
M_upper

array([[-1,  3,  2],
       [ 0, -2,  1],
       [ 0,  0, -2]])

In [28]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M)
v_diag

array([-1, -2, -2])

In [29]:
M_diag = np.diag(v_diag)
M_diag

array([[-1,  0,  0],
       [ 0, -2,  0],
       [ 0,  0, -2]])

In [33]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z])

[(2, 7, -1)]

In [34]:
x = [1,2,3]
y = [1,2,3]
all([x[i] == y[i] for i in range(len(x))])

True

In [35]:
y = [1,2,4]
all([x[i] == y[i] for i in range(len(x))])

False

In [36]:
np.array_equal([1,2], [1,2])

True

In [37]:
np.array_equal(np.array([1,2]), np.array([1,2]))

True

In [38]:
#Bai 3.2:
A = np.reshape(np.arange(36.0), (6,6))
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [41]:
I6 = np.identity(6)
I6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
A.size

36

In [43]:
np.matrix.diagonal(A)

array([ 0.,  7., 14., 21., 28., 35.])

In [44]:
A = A + I6
A

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [45]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
C

array([ 71., 198., 325., 452., 579., 706.])

In [46]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
D

array([[1., 2., 3., 4., 5., 6.],
       [1., 0., 1., 0., 1., 0.]])

In [49]:
E = A.dot(D)
E

ValueError: shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0)

In [50]:
E = D.dot(A)
E

array([[421., 443., 465., 487., 509., 531.],
       [ 37.,  39.,  43.,  45.,  49.,  51.]])

In [52]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
F

array([[1., 1.],
       [2., 0.],
       [3., 1.],
       [4., 0.],
       [5., 1.],
       [6., 0.]])

In [53]:
G

array([[ 71.,   7.],
       [198.,  24.],
       [325.,  43.],
       [452.,  60.],
       [579.,  79.],
       [706.,  96.]])

In [54]:
np.linalg.inv(A)

array([[ 0.37022901, -0.45610687, -0.28244275, -0.10877863,  0.0648855 ,
         0.23854962],
       [-0.44656489,  0.65839695, -0.23664122, -0.13167939, -0.02671756,
         0.07824427],
       [-0.26335878, -0.22709924,  0.80916031, -0.15458015, -0.11832061,
        -0.08206107],
       [-0.08015267, -0.11259542, -0.14503817,  0.82251908, -0.20992366,
        -0.24236641],
       [ 0.10305344,  0.0019084 , -0.09923664, -0.20038168,  0.69847328,
        -0.40267176],
       [ 0.28625954,  0.11641221, -0.05343511, -0.22328244, -0.39312977,
         0.4370229 ]])

In [55]:
#Bai 4:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
b

array([89, 55])

In [57]:
#Bai 5.1:
A = np.array([[2,  3, -1],[4,  1,  2],[-2,  5, -3]])
B = np.array([5, 6, -4])
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, B)
x

array([ 2.875, -1.   , -2.25 ])

In [58]:
np.allclose(np.dot(A, x), B)

True

In [60]:
#Bai 5.2:
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
ngo = sp.solve((pt1, pt2, pt3, pt4))
ngo

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [67]:
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
A_nghichdao = np.linalg.inv(A)
A_nghichdao

LinAlgError: Singular matrix

In [71]:
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
np.linalg.det(A) == 0

True

In [72]:
GT = ('det(A) = 0 --> khong the nghich dao')
GT

'det(A) = 0 --> khong the nghich dao'

In [77]:
#BAI TAP CHUONG 2:
#Cau 1:
#Pb1:
U = np.array = ([1,-1],[2,3])
P = np.array = ([-2,6])
x = np.linalg.solve(U, P)
x

array([0., 2.])

In [82]:
#Pb2:
U = np.array = ([1,-1,0],[2,-1,-1],[1,1,1])
P = np.array = ([2, 3, 6])
x = np.linalg.solve(U, P)
x

array([3., 1., 2.])

In [86]:
#Pb3:
U = np.array = ([1,1,1],[4,2,1],[9,3,1])
P = np.array = ([4, 3, 4])
x = np.linalg.solve(U, P)
x

array([ 1., -4.,  7.])

In [87]:
#Pb4:
U = np.array = ([1,0,1],[1,1,-2],[-2,2,1])
P = np.array = ([1, -3, 0])
x = np.linalg.solve(U, P)
x

array([-0.11111111, -0.66666667,  1.11111111])

In [89]:
#Cau 2:
#Pb1:
eq1 = sp.Eq(x - y, -2)
eq2 = sp.Eq(2*x + 3*y, 6)
ngo = sp.solve((eq1, eq2), (x, y))
ngo

{x: 0, y: 2}

In [90]:
#Pb2:
eq1 = sp.Eq(x - y, 2)
eq2 = sp.Eq(2*x - y - z, 3)
eq3 = sp.Eq(x + y + z, 6)
ngo = sp.solve((eq1, eq2, eq3), (x, y, z))
ngo

{x: 3, y: 1, z: 2}

In [95]:
#Pb3:
eq1 = sp.Eq(x + y + z, 4)
eq2 = sp.Eq(4*x + 2*y + z, 3)
eq3 = sp.Eq(9*x + 3*y + z, 4)
ngo = sp.solve((eq1, eq2, eq3), (x, y, z))
ngo

{x: 1, y: -4, z: 7}

In [96]:
#Pb4:
eq1 = sp.Eq(x + z, 1)
eq2 = sp.Eq(x + y + -2*z, -3)
eq3 = sp.Eq(-2*x + 2*y + z, 0)
ngo = sp.solve((eq1, eq2, eq3), (x, y, z))
ngo

{x: -1/9, y: -2/3, z: 10/9}

In [74]:
#Cau 3:
import numpy as np

def fibonacci_matrix_power(k):
    # Định nghĩa ma trận Fibonacci
    A = np.array([[1, 1],
                  [1, 0]], dtype=object)
    # Lũy thừa ma trận
    Ak = np.linalg.matrix_power(A, k)
    return Ak

def fibonacci(n):
    # Hàm sinh dãy Fibonacci bắt đầu từ F0 = 0
    fibs = [0, 1]
    for i in range(2, n+1):
        fibs.append(fibs[-1] + fibs[-2])
    return fibs

if __name__ == "__main__":
    k = int(input("Nhập số nguyên k: "))
    Ak = fibonacci_matrix_power(k)
    fibs = fibonacci(k+1)
    print(f"A^{k} =\n{Ak}\n")
    print(f"Fibonacci từ F₀ đến F_{k+1}: {fibs}")
    print("Ba phần tử liên tiếp trong dãy Fibonacci:")
    print(f"Phần tử (1,1): F_{k+1} = {fibs[k+1]}")
    print(f"Phần tử (1,2)/(2,1): F_{k} = {fibs[k]}")
    print(f"Phần tử (2,2): F_{k-1} = {fibs[k-1] if k >= 1 else 0}")
    print("\nKiểm chứng:")
    print(f"Ak[0,0] == F_{k+1}? {Ak[0,0] == fibs[k+1]}")
    print(f"Ak[0,1] == F_{k}? {Ak[0,1] == fibs[k]}")
    print(f"Ak[1,0] == F_{k}? {Ak[1,0] == fibs[k]}")
    print(f"Ak[1,1] == F_{k-1}? {Ak[1,1] == (fibs[k-1] if k >= 1 else 0)}")

Nhập số nguyên k: 3
A^3 =
[[3 2]
 [2 1]]

Fibonacci từ F₀ đến F_4: [0, 1, 1, 2, 3]
Ba phần tử liên tiếp trong dãy Fibonacci:
Phần tử (1,1): F_4 = 3
Phần tử (1,2)/(2,1): F_3 = 2
Phần tử (2,2): F_2 = 1

Kiểm chứng:
Ak[0,0] == F_4? True
Ak[0,1] == F_3? True
Ak[1,0] == F_3? True
Ak[1,1] == F_2? True
