In [1]:
# 1. Khái niệm về không gian vector và tích trong
# 1.2.Tích vô hướng, trực giao và ứng dụng
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich)

32


In [2]:
np.dot(a,b)

32

In [3]:
a = np.array([1,2,-3])
np.linalg.norm(a, 2) 

3.7416573867739413

In [4]:
np.linalg.norm(a,1)

6.0

In [5]:
def chuan(v,k):
    tong=0
    for i in range(len(v)):
        tong += abs(v[i]**k)
        kq = math.pow(tong, 1.0/k)
        return kq
import math
chuan(a, 1)

1.0

In [6]:
np.linalg.norm(a,1)

6.0

In [7]:
chuan(a, 2)

1.0

In [8]:
np.linalg.norm(a,2)

3.7416573867739413

In [9]:
 chuan(a, 3)

1.0

In [10]:
np.linalg.norm(a,3)

3.3019272488946263

In [11]:
 chuan(a, 1000)

1.0

In [12]:
np.linalg.norm(a,1000)

C:\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:2568: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

In [13]:
# -->Bị tràn dữ liệu đầu vào

In [14]:
from scipy import linalg
linalg.norm(a)

3.7416573867739413

In [15]:
linalg.norm(a, 100)

3.0

In [16]:
linalg.norm(a, 1000)

C:\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:2568: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

In [17]:
# 2. Đọc thêm: Tổ hợp tuyến tính
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [20]:
v = (1.0/m)*MT.dot(mi)

In [22]:
print(v)

[1.3 0.9 0. ]


In [24]:
# 3. Tri riêng, vector riêng của ma trận và ứng dụng
# 3.1.Bài toán dẫn nhập
import numpy as np
A = np.array([[0.998, 0.136],[0.002, 0.864]])
v0 = np.array([[0.95],[0.05]])
Ap100 = np.linalg.matrix_power(A, 100)
kq = np.dot(Ap100, v0)
print(kq)

[[0.98550723]
 [0.01449277]]


In [25]:
import sympy as sym
x,y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [26]:
# 3.2.Trị riêng và vector riêng của ma trận
import numpy as np
A = np.array([[1, 6],[5, 2]])
u = np.array([[6],[-5]])
Au = np.dot(A, u)
lambda_u = -4 * u
print("A * u =\n", Au)
print("-4 * u =\n", lambda_u)
np.allclose(Au, lambda_u)

A * u =
 [[-24]
 [ 20]]
-4 * u =
 [[-24]
 [ 20]]


True

In [27]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [28]:
print (sympy.pretty(nghiem))

[-7, 3]


In [29]:
# 3.3.Ứng dụng của trị riêng và vector riêng
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
P1

array([[-0.3,  0.9],
       [ 0.3,  0.1]])

In [30]:
A.dot(P)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [31]:
P.dot(D)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [32]:
P @ (D ** 1000) @ P1

array([[-6.25396533e+08, -3.52488701e+08],
       [-3.52488701e+08,  3.14573335e+08]])

In [33]:
D**2

array([[49,  0],
       [ 0,  9]], dtype=int32)

In [34]:
# BÀI TẬP CHƯƠNG 6

In [36]:
# Câu 1: [Trắc nghiệm] Trong Python 3, các câu lệnh sau đây, câu lệnh nào tính chuẩn 2 của
# vector a. Với a được xác định là:
# import numpy as np
# a = np.array([1,2,3])

# a. mag = np.sqrt(a.dot(a))
# b. mag = np.sqrt(a @ a )
# c. mag = np.sqrt(np.inner(a,a))
# d. mag = lambda x : math.sqrt(sum(i** 2 for i in x)) 
#    mag(a) 

In [38]:
# --> Tất cẩ đều đúng.
# --> Chọn a

In [39]:
# Câu 2:
# a)
u = np.array([2, 4, 8])
v = np.array([3, 6, 12])
distance = np.linalg.norm(u - v)
distance

4.58257569495584

In [42]:
# b)
u = np.array([2, 4, 8])
v = np.array([3, 6, 24])
dot_product = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
np.arccos((dot_product / (norm_u * norm_v)))

0.23718680429632516

In [45]:
# c)
u = np.array([3, 4, 5])
v = np.array([11, 13, 15])
projection = (np.dot(u, v) / np.dot(v, v)) * v
print("Vector chiếu p của u lên v:", projection)

Vector chiếu p của u lên v: [3.41747573 4.03883495 4.66019417]
