In [3]:
# Câu 1: Phép toán cơ bản trên vector và ma trận (15 điểm)
import numpy as np
from numpy.linalg import norm
from math import acos, degrees
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3], [1, 4, -2], [0, 2, 5]])
tongAB = A+B
tichAB= 2*A + 3*B
dot= np.dot(A, B)
cos = dot/(norm(A)*norm(B))
goc = degrees(acos(cos))
CtC = np.dot(C, C.T)
print("a) A + B =", tongAB)
print("   2A - 3B =", tichAB)
print("\nb) A · B =", dot)
print("   Góc giữa A và B (độ):", round(goc, 3))
print("\nc) C^T · C =\n", CtC)

a) A + B = [2 3 1 6]
   2A - 3B = [ 3 11  2 14]

b) A · B = -5
   Góc giữa A và B (độ): 99.594

c) C^T · C =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [4]:
# Câu 2: Nhân ma trận, định thức và hạng ma trận (20 điểm)
M = np.array([[2, -1, 3, 0],[1,  4, -2, 5],[0,  2, 6, -3],[-1, 0, 1, 4]])
N = np.array([[1,  3, -2, 0],[4, -1,  5, 2],[0,  2,  3, -1],[-3, 1,  0, 4]])
tichMN = np.dot(M, N)
try:
    detM = np.linalg.det(M)
except np.linalg.LinAlgError:
    detM = "Không phải ma trận vuông"
rankN = np.linalg.matrix_rank(N)
print("a) M x N =\n", tichMN)
print("\nb) Định thức của M =", round(detM, 3))
print("\nc) Hạng của ma trận N =", rankN)

a) M x N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M = 409.0

c) Hạng của ma trận N = 4


In [9]:
# Câu 3: Nghịch đảo ma trận và giải hệ phương trình (25 điểm)
P = np.array([[3, -1, 0, 2],[1,  4, -2, 0],[0,  1,  5, -1],[2,  0,  1, 3]])
b = np.array([6, 8, 3, 7])
detP = np.linalg.det(P)
if detP != 0:
    Pinv = np.linalg.inv(P)
    print("\na) Ma trận nghịch đảo của P:\n", Pinv)
    x = np.dot(Pinv, b)
    print("\nb) Nghiệm của hệ phương trình:\n", x)
    bcheck = np.dot(P, x)
    print(f"x = {x[0]}")
    print(f"y = {x[1]}")
    print(f"z = {x[2]}")
    print(f"w = {x[3]}")
    print("\nc) P * x (kiểm tra lại) =\n", bcheck)
    print("Vector b ban đầu:\n", b)
else:
    print("Ma trận P không khả nghịch")



a) Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]

b) Nghiệm của hệ phương trình:
 [2.         1.71428571 0.42857143 0.85714286]
x = 2.0
y = 1.7142857142857144
z = 0.4285714285714286
w = 0.8571428571428572

c) P * x (kiểm tra lại) =
 [6. 8. 3. 7.]
Vector b ban đầu:
 [6 8 3 7]


In [10]:
# Câu 4: Giá trị riêng, vector riêng và chuẩn hóa (20 điểm)
Q = np.array([[5, -2, 1],[0, 3, -1],[2, 0, 4]])
gtg, vtg = np.linalg.eig(Q)
print("a) Các giá trị riêng của Q:\n", gtg)
print("\nb) Các vector riêng tương ứng:\n", vtg)
n = np.linalg.norm(vtg, axis=0)
vtchuanhoa = vtg / n
print("\nc) Các vector riêng chuẩn hóa:\n", vtchuanhoa)


a) Các giá trị riêng của Q:
 [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]

b) Các vector riêng tương ứng:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]

c) Các vector riêng chuẩn hóa:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


In [16]:
# Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích (20 điểm)
R = np.array([[4, -1, 2],[1, 3, -2],[0, 2, 5]])
b = np.array([12, 5, 9])
x1 = np.linalg.solve(R, b)
print("a) Nghiệm (np.linalg.solve):\n", x1)
detR = np.linalg.det(R)
if detR != 0:
    Rinv = np.linalg.inv(R)
    x2 = np.dot(Rinv, b)
    print("\nb) Nghiệm (dùng nghịch đảo):\n", x2)
    print("So sánh hai nghiệm (x1 == x2?):", np.allclose(x1, x2))
else:
    print("Ma trận R không khả nghịch, không thể tính nghịch đảo.")
frobenius = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của R =", frobenius)


a) Nghiệm (np.linalg.solve):
 [2.78823529 1.52941176 1.18823529]

b) Nghiệm (dùng nghịch đảo):
 [2.78823529 1.52941176 1.18823529]
So sánh hai nghiệm (x1 == x2?): True

c) Chuẩn Frobenius của R = 8.0
