In [2]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] # thử chạy nhiều lần với dãy c dài khác nhau!
M = np.mat([[1,2],[3,4]]) # khởi tạo ma trận 2x2
for i in range(len(c)):
    ci = np.mat([[1,1],[1,0]])
    ci[0, 0] = c[i]
    if (i==0):
        M = ci
    else:
        M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0]) # in số Pi theo dãy số biểu diễn liên phân số.  

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [67]:

X = np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
Y = np.array([[1],[2],[4],[4],[6]])
X






array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [68]:
Y



array([[1],
       [2],
       [4],
       [4],
       [6]])

In [70]:
cv = X.T
cv

array([[1, 1, 1, 1, 1],
       [1, 2, 3, 4, 5]])

In [72]:
A = cv.dot(X)
A

array([[ 5, 15],
       [15, 55]])